version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-laravel-task
    volumes:
      - ./task-list-app:/var/www/html
    ports:
      - "8080:80"
    networks:
      - web
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  mysql:
    image: mysql:8.0
    container_name: mysql-laravel-task
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: taskapp
    ports:
      - "3306:3306"
    networks:
      - web
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  web:
    driver: bridge

volumes:
  mysql-data:
